### ISSUE TITLE
Purchase?

### ISSUE THREAD

**Issue by hamishfagg** [freeheel3r/pressure-regulator#1]
Hi,

Forgive me for making an issue, I'm not sure how else to contact you.

Would you consider selling a few of these? I have a project in mind that requires something like this, and requires fast reaction times which is where you said the commercial options were poor.

Let me know =)
Thanks

**Comment by watsaig** [comment]
Hi,
Thank you for your interest! I don't have any plans for commercialization but some small production may be possible (especially for the manifold which isn't very DIY friendly). Could you send me a message on Hackaday? https://hackaday.io/watsaig
